name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_updated.txt flake8 bandit safety

      - name: Lint with flake8
        run: flake8 .

      - name: Run tests
        run: pytest --cov=.

      - name: Security scan (Bandit)
        run: bandit -r . -ll

      - name: Vulnerability scan (Safety)
        run: safety check --full-report

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-html
          path: htmlcov
